### ISSUE TITLE
Running grpcExtensionOpenVINO tutorial should not give permisssion denied error on accessing shared memory

### ISSUE THREAD

**Issue by mattcowen** [Azure/video-analyzer#85]
I'm running the grpcExtensionOpenVINO topology tutorial against the deployment.openvino.grpc.template deployment. All modules look to be running. I get a protocol error when avaextension:5001 is called.

```
      [IoTHubMonitor] [2:50:57 PM] Message received from [avasample-iot-edge-device/avaedge]:
      {
        "body": {
          "code": "connection_terminated",
          "target": "avaextension:5001",
          "protocol": "grpc"
        },
        "properties": {
          "topic": "/subscriptions/14bbbdfe-3992-46e7-9a9e-65aae95e071a/resourceGroups/ava-record2cloud/providers/Microsoft.Media/videoAnalyzers/avasamplepa4h3hcmivqhq",
          "subject": "/edgeModules/avaedge/livePipelines/Sample-Pipeline-1/processors/grpcExtension",
          "eventType": "Microsoft.VideoAnalyzer.Diagnostics.ProtocolError",
          "eventTime": "2021-11-27T14:50:57.118Z",
          "dataVersion": "1.0"
        },
```
It seems to be a permissions error with access to shared memory

```
    PermissionError: [Errno 13] Permission denied: '/dev/shm/inference_client_share_memory_8406712821321267488'
    Exception ignored in: <function SharedMemoryManager.__del__ at 0x7f2e11b1a5e0>
    Traceback (most recent call last):
      File "/home/video-analytics-serving/samples/lva_ai_extension/common/shared_memory.py", line 145, in __del__
        self._shm_file.close()
    AttributeError: 'SharedMemoryManager' object has no attribute '_shm_file'
    {"levelname": "INFO", "asctime": "2021-11-27 14:41:57,941", "message": "Exception:\n\tFile name: /home/video-analytics-serving/samples/lva_ai_extension/server/media_graph_extension.py\n\tLine number: 85\n\tLine: self.shared_memory_manager = SharedMemoryManager(\n\tValue: [Errno 13] Permission denied: '/dev/shm/inference_client_share_memory_8406712821321267488'", "module": "exception_handler"}
    ERROR:grpc._server:Exception iterating responses: [Errno 13] Permission denied: '/dev/shm/inference_client_share_memory_8406712821321267488'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 453, in _take_response_from_response_iterator
        return next(response_iterator), True
      File "/home/video-analytics-serving/samples/lva_ai_extension/server/media_graph_extension.py", line 330, in ProcessMediaStream
        client_state = State(request.media_stream_descriptor)
      File "/home/video-analytics-serving/samples/lva_ai_extension/server/media_graph_extension.py", line 85, in __init__
        self.shared_memory_manager = SharedMemoryManager(
      File "/home/video-analytics-serving/samples/lva_ai_extension/common/shared_memory.py", line 54, in __init__
        self._shm_file = open(self._shm_file_full_path, 'r+b')
```

I've tried to add a binding for /dev/shm to the deployment and also attempted to use the latest tag, 0.6.1-dlstreamer-edge-ai-extension but I still get permissions denied on the shared memory. e.g. added the following

```
    "avaextension": {
                "version": "1.0",
                "type": "docker",
                "status": "running",
                "restartPolicy": "always",
                "settings": {
                  "image": "intel/video-analytics-serving:0.6.1-dlstreamer-edge-ai-extension",
                  "createOptions": {
                    "ExposedPorts": {
                      "80/tcp": {},
                      "5001/tcp": {}
                    },
                    "HostConfig": {
                      "Binds": ["/tmp:/tmp", "/dev/shm:/dev/shm"],

```

**Comment by mattcowen** [comment]
When i view permissions on /dev/shm i see that the root user is the only one with permissions to update the inference_client_share... file. 

serving@##:~$ ls -l /dev/shm
total 4
-rw-r--r-- 1 vaserving vaserving        4 Nov 27 15:55 foo.txt
-rw-r----- 1 root      root      67108864 Nov 27 15:55 inference_client_share_memory_8406712821321267488

By creating a new container image and setting the following in the dockerfile

``` USER root ```

I'm able to get the tutorial working.

Question: is there a better way of managing this?

**Comment by KishorIoT** [comment]
@mattcowen  - Very sorry that you ran into this issue. We are updating documentation & related sample file to avoid this issue. One recommended way is to use AVA 1.0 container and dlstreamer container with the latest tag.

**Comment by naiteeks** [comment]
@KishorIoT, @mattcowen  - are we ok to close this issue?
